"""Type stubs for the native ``tensorus._native`` extension module."""

from typing import Optional

import numpy as np
import numpy.typing as npt

__version__: str

class Tensorus:
    @staticmethod
    def memory() -> "Tensorus": ...
    @staticmethod
    def local(data_dir: Optional[str] = ...) -> "Tensorus": ...
    @staticmethod
    def connect(uri: str) -> "Tensorus": ...
    @staticmethod
    def version() -> str: ...
    def create_dataset(self, name: str) -> None: ...
    def list_datasets(self) -> list[str]: ...
    def insert(
        self,
        dataset: str,
        array: npt.NDArray[np.float32],
        metadata: Optional[str] = ...,
    ) -> str: ...
    def get(self, dataset: str, id: str) -> npt.NDArray[np.float32]: ...
    def delete(self, dataset: str, id: str) -> None: ...
